import React, { useEffect } from "react";
import Layout from "../Layout/Layout";

function Term() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <Layout>
      <div>
        <div className="bg-gray-100">
          <div className="container mx-auto px-4 py-8">
            <h1 className="text-3xl font-bold mb-4">
              Terms of Use for Information Dissemination
            </h1>

            <p className="mb-4">
              This document constitutes an electronic record in accordance with
              the amended Information Technology Act, 2000 and rules made
              thereunder. This electronic record is generated by a computer
              system and does not require any physical or digital signatures.
              This document is published in compliance with Rule 3 (1) of the
              Information Technology (Intermediaries Guidelines) Rules, 2011,
              which mandates publishing the Terms for accessing or using
              Dialkro’s service via the Dialkro Portal. This document also
              fulfills the requirements specified under Section 65B (2) of the
              Indian Evidence Act, 1872.
            </p>

            <h2 className="text-2xl font-bold mb-2">
              {" "}
              YOUR ACCEPTANCE OF THIS AGREEMENT:
            </h2>

            <p className="mb-4">
              YOUR ACCEPTANCE OF THIS AGREEMENT: This is an agreement between
              you ("you" or "your") and Dialkro, a business directory website
              ("Dialkro," "we," or "our"), which governs your use of the
              services offered by Dialkro through its website www.dialkro.com
              ("Website") and any other medium through which Dialkro provides
              its services (collectively, the "Platforms"). By accessing or
              using any of the Platforms, you agree to be bound by these Terms
              and Conditions ("Terms"). CHANGES: Dialkro reserves the right to
              modify these Terms and the Website without prior notice. It is
              your responsibility to review these Terms periodically for
              updates. All amended Terms will be effective immediately upon
              posting on the Website, and your continued use of the Platforms
              after any such changes signifies your acceptance of the revised
              Terms. HOW YOU MAY USE OUR MATERIALS: Dialkro utilizes a variety
              of information, text, photographs, designs, graphics, images,
              sound and video recordings, animations, content, advertisements,
              and other materials (collectively referred to as "Materials") for
              the purpose of providing business directory services on the
              Platforms. These Materials are provided solely for YOUR PERSONAL
              AND NON-COMMERCIAL USE ONLY.
            </p>

            <h2 className="text-2xl font-bold mb-2">
              {" "}
              HOW YOU MAY USE OUR MARKS
            </h2>

            <p className="mb-4">
              The Dialkro company names, logos, and all related product and
              service names, design marks, and slogans are trademarks and
              service marks owned by and used under license from Dialkro or its
              wholly owned subsidiaries. All other trademarks and service marks
              herein are the property of their respective owners. All copies
              that you make of the Materials on any of the Platforms must bear
              any copyright, trademark, or other proprietary notice located on
              the respective Platforms that pertains to the material being
              copied. You are not authorized to use any Dialkro name or mark in
              any advertising, publicity, or in any other commercial manner
              without the prior written consent of Dialkro. Requests for
              authorization should be made to intproperty@dialkro.com.
            </p>

            <h2 className="text-2xl font-bold mb-2">Security</h2>

            <p className="mb-4">
              We are committed to ensuring that your information is secure. In
              order to prevent unauthorized access or disclosure, we have put in
              place suitable physical, electronic, and managerial procedures to
              safeguard and secure the information we collect online.
            </p>

            <h2 className="text-2xl font-bold mb-2">
              HOW WE MAY USE INFORMATION YOU PROVIDE TO US
            </h2>

            <p className="mb-4">
              Please refrain from sending us any confidential or proprietary
              information. Except for any personally identifiable information
              that we agree to keep confidential as provided in our Privacy
              Policy, any material, including but not limited to any feedback,
              data, answers, questions, comments, suggestions, ideas, or the
              like, which you send to us will be treated as non-confidential and
              non-proprietary. We assume no obligation to protect confidential
              or proprietary information (other than personally identifiable
              information) from disclosure and will be free to reproduce, use,
              and distribute the information to others without restriction. We
              will also be free to use any ideas, concepts, know-how, or
              techniques contained in information that you send us for any
              purpose whatsoever, including but not limited to developing,
              manufacturing, and marketing products and services incorporating
              such information.
            </p>

            <h2 className="text-2xl font-bold mb-2">
              REVIEWS, RATINGS & COMMENTS BY USERS
            </h2>

            <p className="mb-4">
              Since Dialkro provides business directory services through various
              mediums (SMS, WAP, Email, Website, App, and voice or phone), your
              use of any of these mediums to post Reviews, Ratings, and Comments
              about the services listed on Dialkro or its advertisers is subject
              to the following terms and conditions: You are solely responsible
              for the content of any transmissions you make to the Site or any
              transmissions you make to any mediums offered by Dialkro,
              including any materials you add to the Site or add to any mediums
              offered by Dialkro, such as Reviews, Ratings & Comments
              ("Communications"). Dialkro does not endorse or accept any of your
              Communications as representative of their views. By transmitting
              any public Communication to the Site or any other medium provided
              by Dialkro, you grant Dialkro an irrevocable, non-exclusive,
              worldwide, perpetual, unrestricted, royalty-free license (with the
              right to sublicense) to use, reproduce, distribute, publicly
              display, publicly perform, adapt, modify, edit, create derivative
              works from, incorporate into one or more compilations, reproduce,
              and distribute such compilations, and otherwise exploit such
              Communications in all Platforms now known or later developed. You
              confirm and warrant that you have the right to grant these rights
              to Dialkro. You hereby waive and grant to Dialkro all rights,
              including intellectual property rights and "moral rights," in your
              Communications posted at Dialkro through any of its mediums.
              Dialkro is free to use all your Communications as per its
              requirements from time to time. You represent and warrant that you
              own or otherwise control all of the rights to the content that you
              post as Review, Rating, or Comments; that the content is accurate;
              that use of the content you supply does not violate these Terms
              and will not cause injury to any person or entity. For the
              avoidance of doubt, the reference to Communications includes
              reviews, ratings, and comments posted by your tagged friends.
              Dialkro reserves the right to mask or unmask your identity in
              respect of your Reviews, Ratings & Comments posted by you.
            </p>

            <h2 className="text-2xl font-bold mb-2">
              PROHIBITED CONTENT AND USER CONDUCT
            </h2>

            <p className="mb-4">
              Dial kro reserves the right not to upload, distribute, or
              otherwise publish through Dialkro any Communication which: is
              obscene, indecent, pornographic, profane, sexually explicit,
              threatening, or abusive; constitutes or contains false or
              misleading indications of origin or statements of fact; slanders,
              libels, defames, disparages, or otherwise violates the legal
              rights of any third party; causes injury of any kind to any person
              or entity; infringes or violates the intellectual property rights
              (including copyright, patent, and trademark rights), contract
              rights, trade secrets, privacy or publicity rights, or any other
              rights of any third party; violates any applicable laws, rules, or
              regulations; contains software viruses or any other malicious code
              designed to interrupt, destroy, or limit the functionality of any
              computer software or hardware or telecommunications equipment;
              impersonates another person or entity, or collects or uses any
              information about Site visitors.
            </p>

            <p className="mb-4">
              LEGAL ACTION AND INDEMNIFICATION If there are any issues or claims
              arising due to your posts by way of Reviews, Ratings, and
              Comments, Dialkro reserves the right to take appropriate legal
              action against you. You shall indemnify and protect Dialkro
              against such claims, damages, or any issues arising from your
              posting of such Reviews, Ratings, and Comments. Dialkro takes no
              responsibility and assumes no liability for any content posted by
              you or any third party on the Dialkro site or on any mediums of
              Dialkro. USER CONDUCT You acknowledge that conduct prohibited in
              connection with your use of Dialkro includes, but is not limited
              to: Breaching or attempting to breach the security of the Dialkro
              website or any of its mediums. Using any device, software, or
              routine to interfere or attempt to interfere with the proper
              working of the Dialkro website or any transaction being conducted
              on Dialkro. Taking any action that imposes an unreasonable or
              disproportionately large load on the infrastructure of the Dialkro
              website or its systems.
            </p>
          </div>
        </div>
      </div>
    </Layout>
  );
}

export default Term;
